# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsdocumentformat',
            name='file_extension',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='nsdocumentformat',
            name='name',
            field=models.CharField(max_length=31, unique=True),
        ),
    ]
