# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_auto_20170304_1001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nsdocument',
            old_name='document_type_code',
            new_name='document_type',
        ),
        migrations.RenameField(
            model_name='nsdocument',
            old_name='project_code',
            new_name='project',
        ),
    ]
