# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 20:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20170304_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsdocument',
            name='version',
            field=models.CharField(max_length=3),
        ),
    ]
