# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 20:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0005_auto_20170304_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsdocument',
            name='document_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documents.NsDocumentType'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nsdocument',
            name='part_number',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documents.NsPart'),
            preserve_default=False,
        ),
    ]
