# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-04 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0007_auto_20170304_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nsdocument',
            name='version',
        ),
        migrations.AddField(
            model_name='nsdocument',
            name='major_version',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nsdocument',
            name='minor_version',
            field=models.CharField(default=1, max_length=1),
            preserve_default=False,
        ),
    ]
