# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-05 00:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0008_auto_20170304_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nsdocument',
            old_name='part_number',
            new_name='part',
        ),
    ]
