# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0009_auto_20170304_1900'),
    ]

    operations = [
        migrations.CreateModel(
            name='NsDocumentRevision',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', django_extensions.db.fields.CreationDateTimeField(auto_now_add=True, verbose_name='created')),
                ('modified', django_extensions.db.fields.ModificationDateTimeField(auto_now=True, verbose_name='modified')),
                ('revision', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
                'ordering': ('-modified', '-created'),
                'get_latest_by': 'modified',
            },
        ),
        migrations.RemoveField(
            model_name='nsdocument',
            name='major_version',
        ),
        migrations.RemoveField(
            model_name='nsdocument',
            name='minor_version',
        ),
        migrations.AddField(
            model_name='nsdocumentrevision',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documents.NsDocument'),
        ),
    ]
