# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-07 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0010_auto_20170307_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nsdocument',
            name='concise_description',
        ),
        migrations.RemoveField(
            model_name='nsdocument',
            name='document_format',
        ),
        migrations.RemoveField(
            model_name='nsdocument',
            name='document_type',
        ),
        migrations.RemoveField(
            model_name='nsdocument',
            name='filename',
        ),
        migrations.RemoveField(
            model_name='nsdocument',
            name='filepath',
        ),
        migrations.RemoveField(
            model_name='nsdocument',
            name='part',
        ),
        migrations.RemoveField(
            model_name='nsdocument',
            name='project',
        ),
        migrations.RemoveField(
            model_name='nsdocument',
            name='verbose_description',
        ),
        migrations.AddField(
            model_name='nsdocumentrevision',
            name='concise_description',
            field=models.CharField(default='', max_length=63),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nsdocumentrevision',
            name='document_format',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documents.NsDocumentFormat'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nsdocumentrevision',
            name='document_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documents.NsDocumentType'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nsdocumentrevision',
            name='filename',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='nsdocumentrevision',
            name='filepath',
            field=models.FilePathField(default='', match='//Nucleus-NAS1/Nucleus/PROJECTS/*', unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nsdocumentrevision',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documents.NsProject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nsdocumentrevision',
            name='verbose_description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.DeleteModel(
            name='NsPart',
        ),
    ]
