# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 20:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0012_auto_20170307_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nsdocumentrevision',
            name='document_type',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='documents.NsDocumentType'),
        ),
    ]
