# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 22:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0013_auto_20170308_1509'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nsdocumentrevision',
            options={},
        ),
        migrations.AlterField(
            model_name='nsdocumentrevision',
            name='document_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='documents.NsDocumentType'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='nsdocumentrevision',
            unique_together=set([('project', 'revision')]),
        ),
    ]
