# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-08 22:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0014_auto_20170308_1715'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='nsdocumentrevision',
            unique_together=set([('document', 'revision')]),
        ),
    ]
